relative_templates/learn_app/urls.py
from django.conf.urls import url
from learn_app import views

# TEMPLATE TAGGING
app_name = 'learn_app' # look under here to find matching url

urlpatterns = [
	url(r'^relative/', views.relative, name='relative'),
	url(r'^other/$', views.other, name='other'),
	]

relative_templates/relative_templates/urls.py
from django.contrib import admin
from django.urls import path
from learn_app import views
from django.conf.urls import url, include


urlpatterns = [
	url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^learn_app/', include('learn_app.urls') )
]

relative_templates/learn_app/models.py
from django.db import models

# Create your models here.

relative_templates/learn_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict = {'text':'hello world', 'number':100}
	return render(request, 'learn_app/index.html', context_dict)

def other(request):
	return render(request, 'learn_app/other.html')

def relative(request):
	return render(request, 'learn_app/relative_url_templates.html')

relative_templates/templates/learn_app/base.html
<!DOCTYPE html>
<html>
 <head>
	<meta charset="utf-8">
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
 </head>
 <body>
 	<nav class="navbar navbar-default navbar-static-top">
 		<div class = "container">
 			<ul class="nav navbar-nav">
 				<li class="navbar-brand"><a href="{% url 'index' %}">BRAND</a></li>
 				<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
 				<li><a class="navbar-link" href="{% url 'learn_app:other' %}">Other</a></li>
 			</ul>
 		</div>
 	</nav>

 	<div class="container">
 		<!-- template tag will be set up here now, this is the base that 
 		we want for all other web pages -->

 		{% block body_block %}
 		<!-- Anything outside of this will be inherited if you extend! -->
 		{% endblock %}

 	</div>


  </body>
 </html>

relative_templates/templates/learn_app/index.html
<!DOCTYPE html>
{% extends "learn_app/base.html" %}
	{% block body_block %}
 	<h1>WELCOME TO INDEX</h1>
 	<h2>This be index.html page showing</h2>
 	<h1>{{ text|cut:'world' }}</h1>
 	<h1>{{ number|add:"99" }}</h1>
 	{% endblock %}

relative_templates/templates/learn_app/other.html
<!DOCTYPE html>
{% extends "learn_app/base.html" %}
	{% block body_block %}
 	<h1>WELCOME TO OTHER</h1>
	<h2>THIS IS EX OF TEMPLATE INHERITANCE</h2>
	{% endblock %}

relative_templates/templates/learn_app/relative_url_templates.html
<!DOCTYPE html>
<html>
 <head>
	<meta charset="utf-8">
	<title></title>
 </head>
 <body>
 	<h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
 	<a href="{% url 'learn_app:other' %}"> THE OTHER PAGE</a>
 	<a href="{% url 'index' %}">LINK TO INDEX</a>
  </body>
 </html>